liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # define your filter sets under this option
    filter_sets:
        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        thumb_369_220:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [369, 220]
                    mode:          outbound
                    allow_upscale: true
        thumb_235_108:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [235, 108]
                    mode:          outbound
                    allow_upscale: true
        thumb_870_521:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [870, 521]
                    mode:          outbound
                    allow_upscale: true
        thumb_1900_1068:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [1900, 1068]
                    mode:          outbound
                    allow_upscale: true
        thumb_980_688:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [980, 688]
                    mode:          outbound
                    allow_upscale: true
        thumb_523_397:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [523, 397]
                    mode:          outbound
                    allow_upscale: true
        thumb_478:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [478, 478]
                    mode:          outbound
                    allow_upscale: true
        thumb_378_283:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [378, 283]
                    mode:          outbound
                    allow_upscale: true
        thumb_569_285:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [569, 285]
                    mode:          outbound
                    allow_upscale: true
        thumb_903_452:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [903, 452]
                    mode:          outbound
                    allow_upscale: true
        thumb_406_341:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [406, 341]
                    mode:          outbound
                    allow_upscale: true
        thumb_619_436:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [619, 436]
                    mode:          outbound
                    allow_upscale: true
        thumb_1900_1000:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [1900, 1000]
                    mode:          outbound
                    allow_upscale: true