liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # define your filter sets under this option
    filter_sets:
        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        thumb_medium:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [369, 220]
                    mode:          outbound
                    allow_upscale: true
        thumb_partner:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [235, 108]
                    mode:          outbound
                    allow_upscale: true
        thumb_service:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [570, 388]
                    mode:          outbound
                    allow_upscale: true
        thumb_blog:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [870, 521]
                    mode:          outbound
                    allow_upscale: true
        thumb_ip_adn:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [1900, 1068]
                    mode:          outbound
                    allow_upscale: true
        thumb_ip_item_adn:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [980, 688]
                    mode:          outbound
                    allow_upscale: true
        thumb_ip_item_adn_small:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [523, 397]
                    mode:          outbound
                    allow_upscale: true
        thumb_approch:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [478, 478]
                    mode:          outbound
                    allow_upscale: true
        thumb_metier:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip:
                thumbnail:
                    size:          [378, 283]
                    mode:          outbound
                    allow_upscale: true