vich_uploader:
    db_driver: orm
    mappings:
        section_image:
            uri_prefix: /images/section
            upload_destination: '%kernel.project_dir%/public/images/section'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid
        post_image:
            uri_prefix: /images/post
            upload_destination: '%kernel.project_dir%/public/images/post'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid
        partner_image:
            uri_prefix: /images/partner
            upload_destination: '%kernel.project_dir%/public/images/partner'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid